Update Prices Server to include USCPI API
Signo-App/prices-server pull request #8
Opened 2023-01-26 13:59 UTC by krisoshea-eth

Added the fetchUscpiOrError function to fetch USCPI data from the Kapsarc API. This API allows the prices server to query the Kapsarc database for USCPI data at specific time intervals.

2023-01-27 09:25 UTC, KohliSuraj commented
> Added the fetchUscpiOrError function to fetch USCPI data from the Kapsarc API. This API allows the prices server to query the Kapsarc database for USCPI data at specific time intervals.

Apt description 👌

2023-01-27 09:27 UTC, KohliSuraj commented on fetchall.py
> +def fetchUscpiOrError(year, month):
This function is not using a key when making the API call.

2023-01-27 09:29 UTC, KohliSuraj requested changes

2023-01-27 09:29 UTC, KohliSuraj commented on fetchall.py
> +def fetchUscpiOrError(year, month):
This function is not using a key when making the API call and thus returning an ERR as value.

2023-01-27 09:32 UTC, KohliSuraj commented
The KAPSARC API looks complex to me, can we simplify it?

The stlouisfed gov API looks easier in comparison -> [https://api.stlouisfed.org/fred/series/observations?series_id=CPIAUCSL&api_key=API_KEY&file_type=json&observation_start=2022-12-01](https://api.stlouisfed.org/fred/series/observations?series_id=CPIAUCSL&api_key=API_KEY&file_type=json&observation_start=2022-12-01) but the down side for that is that we don't have a nice UI for it ...

@krisoshea-eth What do you think?

2023-01-30 19:57 UTC, krisoshea-eth commented on fetchall.py
> +def fetchUscpiOrError(year, month):
I had included this loadKapsarcApiKey function as a placeholder as it didn't make sense to me that I could query the database without an API key. However, I didn't realise that this would cause an error. 

I have just removed the loadKapsarcApiKey function and its references. The fetchUscpiOrError function appears to be working normally now.

2023-01-30 19:58 UTC, krisoshea-eth commented
>

2023-01-30 20:58 UTC, krisoshea-eth commented
> 

I personally found the st louis fed API quite difficult to navigate from a user's perspective. I'm not sure if it is easier to implement on the prices server though, I would definitely trust your judgement on that. I found it easy to determine the price for a given time interval using Kapsarc. Alternatively, we could potentially use the st louis fed API for the price server but direct users to the kapsarc API UI as there shouldn't be any discrepancies in price. In that sense, we should get the best of both worlds, a more straightforward implementation for the prices server and a simple UI experience for the user. What do you think? @KohliSuraj  We may also be able to simplify the Kapsarc API. What did you find complex about the Kapsarc API compared to the St Louis Fed API?

2023-02-01 09:11 UTC, KohliSuraj approved these changes

2023-02-01 16:05 UTC, merged